# Generated by Django 3.0.8 on 2020-08-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20200807_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postspage',
            name='content',
        ),
        migrations.RemoveField(
            model_name='postspage',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='postspage',
            name='title',
        ),
        migrations.RemoveField(
            model_name='postspage',
            name='update',
        ),
        migrations.RemoveField(
            model_name='postspage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='postspage',
            name='width_field',
        ),
        migrations.AddField(
            model_name='postspage',
            name='cat',
            field=models.CharField(blank=True, choices=[('C', 'Chains & Necklaces'), ('B', 'Bangles & Bracelets'), ('R', 'Rings'), ('P', 'Pendants'), ('J', 'Jewellery Sets'), ('N', 'Nose Rings & Pins'), ('H', 'Hair Accessories'), ('T', 'Toe Rings'), ('A', 'Anklets'), ('B', 'Body Jewellery'), ('M', 'Mangalsutras & Tanmaniyas')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='postspage',
            name='image',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
