# Generated by Django 3.0.8 on 2020-08-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_postspage_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postspage',
            name='cat',
            field=models.CharField(blank=True, choices=[('Chains & Necklaces', 'Chains & Necklaces'), ('Bangles & Bracelets', 'Bangles & Bracelets'), ('Rings', 'Rings'), ('Pendants', 'Pendants'), ('Jewellery Sets', 'Jewellery Sets'), ('Nose Rings & Pins', 'Nose Rings & Pins'), ('Hair Accessories', 'Hair Accessories'), ('Toe Rings', 'Toe Rings'), ('Anklets', 'Anklets'), ('Body Jewellery', 'Body Jewellery'), ('Mangalsutras & Tanmaniyas', 'Mangalsutras & Tanmaniyas')], max_length=30, null=True),
        ),
    ]
