# Generated by Django 3.0.8 on 2020-08-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_postspage_ran'),
    ]

    operations = [
        migrations.AddField(
            model_name='postspage',
            name='content',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='postspage',
            name='ran',
            field=models.CharField(blank=True, choices=[('Below 100', 'Below 100'), ('100-200', '100-200'), ('200-300', '200-300'), ('300-400', '300-400'), ('400-500', '400-500'), ('500-600', '500-600'), ('600-700', '600-700'), ('700-800', '700-800'), ('800-900', '800-900'), ('Above 1000', 'Above 1000')], max_length=30, null=True),
        ),
    ]
