# Generated by Django 3.0.8 on 2020-08-11 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20200811_2220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postspage',
            old_name='cat',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='postspage',
            old_name='ran',
            new_name='range',
        ),
    ]
