# Generated by Django 3.0.8 on 2020-08-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20200812_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='postspage',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
