# Generated by Django 3.0.1 on 2020-08-17 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_postspage_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postspage',
            name='style',
        ),
        migrations.AlterField(
            model_name='postspage',
            name='category',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
